= Lightroom Classic Catalogs on Network Attached Storage

== Background
I currently have about 30K photos (>1TB) stored on a QNAP TS-253D NAS 
(Network Attached Storage) device with a capacity of 6TB (mirrored). The 
NAS is connected by 10Gbps Ethernet (1Gbps Ethernet also works well) to 
a custom-built PC and a mini PC, both running Windows 10 Home. To make 
storage management as simple as possible, the PC and laptop are 
configured _dataless_: virtually all files that must be backed up are 
stored on the NAS<<dataless>>, which runs 
https://duplicacy.com/[Duplicacy]<<duplicacy>> to back up files nightly 
to external RAID 5 DAS (Direct Attached Storage) and off-site to 
https://www.backblaze.com/b2/cloud-storage.html/[Backblaze B2]<<b2>>. In 
particular, each user's `Pictures` folder is located in their home 
folder on the NAS. The capacity of the NAS can be easily expanded by 
replacing the mirrored drives one-at-a-time with larger drives. The PCs 
don't need much local storage, so they have only two 256GB SSDs, one for 
system files and applications and one for temporary files as needed by 
Photoshop and other applications. 

I've been accessing the same Lightroom Classic (_LrC_) catalogs on a
NAS since 2011, except for a few months in 2016 after replacing a
Netgear ReadyNAS with a QNAP TS-251+, which had a defective SMB
implementation that caused _LrC_ and other failures.  During this
period I modified the `lightroom.ffs_batch` and `full.ffs_batch` files
described below to copy the catalog `*.lrcat*` files in addition to
the settings to/from an internal SSD as a temporary, unreliable
workaround.

*NOTE:* I *_do not_* recommend QNAP: poor software quality, inadequate
software regression testing, security vulnerabilities, bloatware, poor
support, poor documentation.

== CAUTION!
Lightroom Classic (_LrC_) normally will not access a catalog that 
resides on a network drive. In 2007, Adobe engineer Dan 
Tull<<Rellis>><<Tull>> tested _LrC_ catalogs on a corporate network 
drive by disconnecting the cable and observed catalog corruption, so 
Adobe coded _LrC_ to disallow them on network drives. Technically, 
however, network drives are designed to _look, smell, feel, and act like 
your own disk space_.<<SAMBA>> An _LrC_ catalog is an SQLite<<SQLite>> 
database, the integrity of which is maintained via standard Windows file 
operations<<WAL>>, which are also supported by SMB<<SMB>>, the protocol 
Windows uses to access files on network drives. Thus, catalog corruption 
is the result of hardware failure or software defects, not inherent 
technical limitations or 
incompatibilities.<<network>><<multi>><<threads>><<corrupt>> But since 
more hardware and software is involved in accessing network-attached 
storage than internal or directly-attached external storage, the risk of 
catalog corruption is greater. However, there is also risk in other 
methods proposed<<risky>> for using a catalog from multiple machines, 
such as inadvertently disconnecting an external hard drive while 
Lightroom is running or while synchronizing with Dropbox, Google Drive, 
One Drive, etc. 

Also, _LrC_ currently requires that the `Previews.lrdata` folder must
reside in the same folder as the catalog. Thus, when the catalog is on
a network drive, previews will also reside there, possibly slowing
performance.

Setting up the NAS:

  * with an uninterruptible power supply (UPS), to protect against
	power failures,
	
  * with RAID, to protect against single-drive failures, and
  
  * as an "always up" device automatically running nightly backups,
	when _LrC_ catalogs are less likely to be in use,
	
provides protections not typically provided on desktop PCs that offset
the added risk of storing and accessing catalogs on the NAS.

== Basic Setup
_LrC_ will create and access catalogs on a network folder
(`\\NAS0\home\Pictures\Lightroom` in this example) by means of a
Windows 10 _junction_ (`%HOMEPATH%\Lightroom` in this example).

For each _<user>_ on each machine running _LrC_:

. Run `cmd` as Administrator and execute the following commands:
+
		cd %HOMEPATH%\..\<user>
		mklink /d Lightroom-symlink "\\NAS0\home\Pictures\Lightroom"
		mklink /j Lightroom Lightroom-symlink
+
Be sure to use the same junction name for a given user on all PCs if 
synchronizing _LrC_ settings across PCs as described below.

. If necessary, move catalogs folders to the network folder, e.g. to
	`%HOMEPATH%\Lightroom\Catalogs`.

. Run _LrC_ while holding the `Alt` key to open the _Select Catalog_
	dialog, and either _Choose a Different Catalog_ or _Create a New Catalog_
	in a folder below the junction, e.g. to `%HOMEPATH%\Lightroom\Catalogs\Master`.

When _LrC_ opens a catalog, it creates a `.lrcat.lock` file in the
catalog's folder, which prevents other instances of _LrC_ from accessing
the same catalog at the same time.<<lock>>  However, if _LrC_ crashes or is
running when "Sleep", or "Switch user" is done, the catalog is left
locked and cannot be accessed by other users or machines.  Also, while
_LrC_ has a catalog open, any copy made of the catalog by another
application such as Windows File History, Backup and Restore, Acronis,
Macrium, Carbonite, CrashPlan, Google Drive, One Drive, Dropbox,
etc. is not guaranteed to capture the catalog in a consistent state;
thus, such a backup is not reliably valid.

  * Periodically check the integrity of and back up catalogs with _LrC_,
    and back up these backups.

  * Install `gracefulexit.bat` (instructions are in that file) and use
    it to put a PC to sleep, switch user, and logoff.

  * *OPTIONAL:* To reduce occurrences of abandoned file locks<<veto>>, disable
	Windows oplocks on `.lock files` (and FreeFileFileSync
	`sync.ffs_db` databases, see below) by adding the following to
	`/etc/smb.conf` on the NAS:

		veto oplock files = /*.lock/sync.ffs_db/

== *OPTIONAL:* Synchronize _LrC_ settings<<LrCprefs>> across all PCs

_LrC_ changes settings files frequently when running, so synchronization
is implemented by running _LrC_ via a shortcut which, in turn, runs
a file synchronization utility (_FreeFileSync_ in this case) before and
after running _LrC_ to sync settings from/to a folder on the NAS:

	C:\Windows\System32\cmd.exe /c ""%AppData%\FreeFileSync\Config\lightroom.ffs_batch" && "%ProgramFiles%\Adobe\Adobe Lightroom Classic\Lightroom.exe" & "%AppData%\FreeFileSync\Config\lightroom.ffs_batch""

. Install https://www.freefilesync.org[FreeFileSync] (_FFS_).

. Create `%AppData%\FreeFileSync\Config` folders to store each
   user's `lightroom.ffs_batch` file.
   
. Create `%AppData%\FreeFileSync\Logs` folders to store each user's
   _FFS_ logs.

. Create folders on the NAS for each user's _LrC_ settings, e.g.:

		\\<my NAS>\home\AppData\Roaming\Adobe\Lightroom

. Edit `lightroom.ffs_batch` with _FFS_ to change `NAS0` to
   the name of your NAS.

. For each user, run _LrC_ on the machine on which the latest _LrC_
   settings reside to sync these to the NAS, then open
   `lightroom.ffs_batch` with _FFS_ on all other machines and manually
   sync the _LrC_ settings from the NAS to `%AppData%\Adobe\Lightroom`.

. Pin the `lightroom` shortcut to each user's Start Menu and/or
   taskbar (https://www.digitalcitizen.life/how-pin-special-windows-shortcuts-taskbar).

== *OPTIONAL:* Synchronize _LrC_ plug-ins across all PCs

_LrC_ plug-ins are synchronized when updated by a file synchronization
utility (_FreeFileSync_ in this case).  For each machine:

. Install https://www.freefilesync.org)[_FreeFileSync_] (_FFS_).

. Create the `%CommonProgramFiles%\FreeFileSync\Config` folder to
   store the `Realtime.ffs_batch` and `Realtime.ffs_real` files.

. Create the `%CommonProgramFiles%\FreeFileSync\Log` folder to store
   _FFS_ logs.

. Create a folder on the NAS to store the _FFS_
   `Realtime.ffs_batch` and `Realtime.ffs_real` files, e.g.:

		\\<my NAS>\<my path>\FreeFileSync\Common Files\Config

. Create a folder on the NAS to store _LrC_ plug-ins, e.g.:

		\\<my NAS>\<my path>\Lightroom\LR Plugins

. Assure that a user account e.g. `myaccount`, has RW permission
   on:
   
	* `%CommonProgramFiles%\LR Plugins` and subfolders

	* `%CommonProgramFiles%\FreeFileSync` and subfolders

	* `\\<my NAS>\<my path>\Lightroom\LR Plugins` and subfolders
   
	* `\\<my NAS>\<my path>\FreeFileSync\Common Files\Config` and subfolders

. Edit `%CommonProgramFiles%\FreeFileSync\Config\Realtime.ffs_batch` with
   _FFS_ to change the path names to match those of your NAS folders.
   A folder pair to synchronize `%Public%\Pictures\Screen Saver Photos`
   is included; remove if not wanted.

. Open `Realtime.ffs_batch` with _FFS_ on the machine on which the
   latest _LrC_ plug-ins reside, sync these to the NAS, then open
   `Realtime.ffs_batch` with _FFS_ on all other machines and manually
   sync the _LrC_ plug-ins from the NAS to `%ProgramFiles%\Common
   Files\LR Plugins`.
   
. Create the `Realtime.ffs_real` file (see https://freefilesync.org/manual.php?topic=realtimesync):

	* run `"%PROGRAMFILES%\Program Files\FreeFileSync\RealTimeSync.exe"`
	
	* File -> Open `%CommonProgramFiles%\FreeFileSync\Config\Realtime.ffs_batch`
	
	* File -> Save as `Realtime.ffs_real`

. https://www.sevenforums.com/tutorials/67503-task-create-run-program-startup-log.html[Create a Task Scheduler task] to
   run RealTimeSync at system startup:

	* Run under a user account (e.g. `myaccount`) that has read and write
      permission on all synced folders

	* Run whether user is logged on or not
	
	* Trigger: At startup
	
	* Action: Start a program `"%ProgramFiles%\FreeFileSync\RealTimeSync.exe"`
	
	* Add arguments: `"%CommonProgramFiles%\FreeFileSync\Config\Realtime.ffs_real"`

	* Settings: Do not start a new instance

1. Restart, then check the `%CommonProgramFiles%\FreeFileSync\Log` folder to confirm that folders
are synchronizing.

== *OPTIONAL:* Synchronize Photoshop preferences across all machines

Photoshop, Bridge, CameraRaw, Color, LensCorrection, and Plugins preferences<<PSprefs>> are
synchronized when updated by a file synchronization utility
(_FreeFileSync_ in this case), and also by `gracefulexit.bat`
on sleep, switch user, and logoff.

. Create a folder on the NAS for each user's Photoshop preferences, e.g.:
+
		\\<my NAS>\home\AppData\Roaming\Adobe

. Copy the following files to each user's `%AppData%\FreeFileSync\Config` folder:

		full.ffs_batch
		watched.ffs_batch

. Edit these files to change `NAS0` to the name of your NAS.  Folder
pairs for the `Affinity` settings, `Desktop`, and `Favorites` are
included; remove if not wanted.

. For each user, open `full.ffs_batch` with _FFS_ on the machine on 
which the latest Photshop preferences reside, sync these to the NAS, then 
open `full.ffs_batch` with _FFS_ on all other machines and manually 
sync the setting from the NAS to the local machine. 

   
. Create the `watched.ffs_real` file (see https://freefilesync.org/manual.php?topic=realtimesync):

	* run `"%PROGRAMFILES%\FreeFileSync\RealTimeSync.exe"`
	
	* File -> Open `%AppData%\FreeFileSync\Config\watched.ffs_batch`
	
	* File -> Save as `%AppData%\FreeFileSync\Config\watched.ffs_real`

. Copy the `RealTimeSync` shortcut to each user's Startup folder:

		%AppData%\Microsoft\Windows\Start Menu\Programs\Startup

. Login as each user and check the `%AppData%\FreeFileSync\Logs`
folder to confirm that folders are synchronizing.

== References

[bibliography]
* [[[dataless,1]]] _How to Change the Location of User Folders in Windows 10_, https://www.dummies.com/computers/operating-systems/windows-10/how-to-change-the-location-of-user-folders-in-windows-10/

* [[[duplicacy,2]]] _Duplicacy: A lock-free deduplication cloud backup tool_, https://github.com/gilbertchen/duplicacy

* [[[b2,3]]] _Backblaze B2 Storage_, https://duplicacy.com/backblaze.html

* [[[Rellis,4]]] link:https://community.adobe.com/t5/lightroom-classic/operating-lightroom-cc-classic-via-network-drive/m-p/9997623?page=1#M115849[_Post by johnrellis on_ `feedback.photoshop.com`]

* [[[Tull,5]]] link:++https://feedback.photoshop.com/photoshop_family/topics/multi_user_multi_computer?topic-reply-list[settings][filter_by]=all&topic-reply-list[settings][reply_id]=5744549#reply_5744549++[_Reply by Dan Tull, Adobe Employee on_ `feedback.photoshop.com`]

* [[[SAMBA,6]]] _SMB Filesystems for Linux_, https://www.samba.org/samba/docs/SambaIntro.html

* [[[SQLite,7]]] _SQLite_ https://sqlite.org

* [[[WAL,8]]] _Write-Ahead Logging_, https://sqlite.org/wal.html

* [[[SMB,9]]] _Server Message Block_, https://en.wikipedia.org/wiki/Server_Message_Block

* [[[network,10]]] _Client/Server Applications_, https://www.sqlite.org/whentouse.html

* [[[multi,11]]] _(5) Can multiple applications or multiple instances of the same application access a single database file at the same time?_, https://www.sqlite.org/faq.html#q5

* [[[threads,12]]] _(6) Is SQLite threadsafe?_, https://www.sqlite.org/faq.html#q6

* [[[corrupt,13]]] _How To Corrupt An SQLite Database File_, https://www.sqlite.org/howtocorrupt.html

* [[[risky,14]]] _Sharing Lightroom Catalog with Multiple Computers_, https://photographylife.com/sharing-lightroom-catalog-with-multiple-computers

* [[[lock,15]]] _Error: Lightroom catalog cannot be opened, More information_, https://helpx.adobe.com/lightroom-classic/kb/lightroom-error-catalog-cannot-be-opened-lrcat-lock.html

* [[[veto,16]]] _How to prevent samba from holding a file lock after a client disconnects_, https://serverfault.com/questions/204812/how-to-prevent-samba-from-holding-a-file-lock-after-a-client-disconnects

* [[[LrCprefs,17]]] _Preference file and other file locations | Lightroom Classic_, https://helpx.adobe.com/lightroom-classic/kb/preference-file-and-other-file-locations.html

* [[[PSprefs,18]]] _Preference file functions, names, locations | Photoshop_, https://helpx.adobe.com/photoshop/kb/preference-file-names-locations-photoshop.html
